blank_issues_enabled: false
contact_links:
  - name: ğŸ‘¨â€ğŸ’» Support
    url: "https://github.com/FrankLucky1"
    about: Get direct help from the author of this project
  - name: ğŸŒŸ Sponsor
    url: https://github.com/sponsors/bankole2000
    about: Like this project? Please consider supporting the author.s